/*
 * MePlotView.java
 */
package seplot;

import java.awt.Graphics;
import java.awt.event.KeyEvent;

import javax.swing.GroupLayout.ParallelGroup;
import javax.swing.GroupLayout.SequentialGroup;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import meplot.expressions.Expression;
import meplot.expressions.ISubstitutible;
import meplot.expressions.exceptions.DerivationException;
import meplot.expressions.numbers.Int;
import meplot.expressions.visitors.derivative.DerivativeHelper;
import meplot.expressions.visitors.simplification.SimplificationHelper;
import meplot.graphics.DrawController;
import meplot.graphics.graphs.GraphList;
import meplot.graphics.graphs.NormalGraph;
import meplot.graphics.graphs.ParametricGraph;
import meplot.parser.Parser;
import meplot.parser.ParserException;
import meplot.parser.utils.Cleaner;

import org.jdesktop.application.Action;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.SingleFrameApplication;

import platform.log.FilterLogger;
import platform.log.Log;
import platform.log.LogLevel;

/**
 * The application's main frame.
 *
 * @author Leonardo Taglialegne
 */
public class SePlotView extends FrameView{

	public SePlotView(final SingleFrameApplication app){
		super(app);
		Log.setLogger(new FilterLogger(LogLevel.WARNING, new MessageLogger()));
		initComponents();
	}

	@Action
	public void showAboutBox(){
		if(aboutBox == null){
			final JFrame mainFrame = SePlotApp.getApplication().getMainFrame();
			aboutBox = new SePlotAboutBox(mainFrame);
			aboutBox.setLocationRelativeTo(mainFrame);
		}
		SePlotApp.getApplication().show(aboutBox);
	}

	private DrawController dc;

	@Action
	public void plot(){
		ISubstitutible expr = Int.ZERO;
		try{
			final String s = expressionBox.getText();
			if(s.indexOf(';') >= 0){
				parametricParse(s);
				return;
			}
			expr = Parser.parse(s);
			expr = expr.applyConstants();
		}
		catch(final ParserException ex){
			JOptionPane.showMessageDialog(null, "Parser error!");
		}
		final int width = jPanel1.getWidth();
		final int heigth = jPanel1.getHeight();
		if(dc == null)
			dc = new DrawController();

		/*
		 * int mode = DrawController.CONTOUR;
		 * switch(jComboBox1.getSelectedIndex()){ case 2: mode =
		 * DrawController.XYSCAN; break; case 3: mode = DrawController.XYSCAN;
		 * break; case 4: if(jCheckBox1.isSelected()){ mode =
		 * DrawController.CONTOUR; } else{ mode = DrawController.CLEANCONTOUR; }
		 * break; case 5: if(jCheckBox1.isSelected()){ mode =
		 * DrawController.GRAYCONTOUR; } else{ mode =
		 * DrawController.GRAYCLEANCONTOUR; } break; case 6: mode =
		 * DrawController.THREED; break; case 7: mode = DrawController.FIELD;
		 * break; default: break; } dc.mode = mode;
		 */

		final GraphList gl = new GraphList();
		gl.add(new NormalGraph(expr, 0xFF0000));
		final Graphics g = jPanel1.getGraphics();
		final FakeGraphics fg = new FakeGraphics(g);

		dc.doPaint(fg, gl, width, heigth);
		g.dispose();
	}

	private void parametricParse(final String s){
		final int splitPoint = s.indexOf(";");
		final String y = s.substring(0, splitPoint);
		final String x = s.substring(splitPoint + 1, s.length());
		final ISubstitutible fy = getExpression(y);
		final ISubstitutible fx = getExpression(x);

		final int width = jPanel1.getWidth();
		final int heigth = jPanel1.getHeight();
		if(dc == null)
			dc = new DrawController();

		final GraphList gl = new GraphList();

		gl.add(new ParametricGraph(fy, fx, 0xFF0000));
		final Graphics g = jPanel1.getGraphics();
		final FakeGraphics fg = new FakeGraphics(g);

		dc.doPaint(fg, gl, width, heigth);
		g.dispose();
	}

	private static ISubstitutible getExpression(final String y){
		try{
			return Parser.parse(y);
		}
		catch(final ParserException ex){
			Log.log(LogLevel.ERROR, "Parser exception:", ex.getMessage());
			return Int.ZERO;
		}
	}

	// should add @suppress unchecked?
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings({"deprecation"})
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents(){

		mainPanel = new javax.swing.JPanel();
		expressionBox = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		dBox = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		ddBox = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jPanel1 = new javax.swing.JPanel();
		jComboBox1 = new javax.swing.JComboBox();
		jCheckBox1 = new javax.swing.JCheckBox();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		jButton9 = new javax.swing.JButton();
		menuBar = new javax.swing.JMenuBar();
		final javax.swing.JMenu fileMenu = new javax.swing.JMenu();
		final javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();

		mainPanel.setName("mainPanel"); // NOI18N
		mainPanel.addKeyListener(new java.awt.event.KeyAdapter(){
			public void keyReleased(final java.awt.event.KeyEvent evt){
				mainPanelKeyReleased(evt);
			}
		});

		expressionBox.addFocusListener(new java.awt.event.FocusAdapter(){
			public void focusLost(final java.awt.event.FocusEvent evt){
				expressionBoxFocusLost(evt);
			}
		});
		expressionBox.addKeyListener(new java.awt.event.KeyAdapter(){
			public void keyPressed(final java.awt.event.KeyEvent evt){
				expressionBoxKeyPressed(evt);
			}
		});

		final org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application
				.getInstance(seplot.SePlotApp.class).getContext()
				.getResourceMap(SePlotView.class);
		jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N

		jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N

		dBox.setFont(resourceMap.getFont("dBox.font")); // NOI18N
		dBox.setText(resourceMap.getString("dBox.text")); // NOI18N

		jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N

		ddBox.setFont(resourceMap.getFont("ddBox.font")); // NOI18N
		ddBox.setText(resourceMap.getString("ddBox.text")); // NOI18N

		final javax.swing.ActionMap actionMap = org.jdesktop.application.Application
				.getInstance(seplot.SePlotApp.class).getContext()
				.getActionMap(SePlotView.class, this);
		jButton1.setAction(actionMap.get("plot")); // NOI18N
		jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
		jButton1.setName("jButton1"); // NOI18N
		jButton1.addKeyListener(new java.awt.event.KeyAdapter(){
			public void keyPressed(final java.awt.event.KeyEvent evt){
				jButton1KeyPressed(evt);
			}
		});

		jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(
				0, 0, 0)));
		jPanel1.setName("jPanel1"); // NOI18N
		jPanel1.addKeyListener(new java.awt.event.KeyAdapter(){
			public void keyPressed(final java.awt.event.KeyEvent evt){
				jPanel1KeyPressed(evt);
			}
		});

		final javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 510, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 331, Short.MAX_VALUE));

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(
				new String[]{"Explicit graph", "Explicit graph, no f'", "Implicit graph",
						"Complex conjugate", "Contour plot", "Gray plot", "3D plot",
						"Field plot"}));
		jComboBox1.setName("jComboBox1"); // NOI18N

		jCheckBox1.setSelected(true);
		jCheckBox1.setLabel(resourceMap.getString("jCheckBox1.label")); // NOI18N
		jCheckBox1.setName("jCheckBox1"); // NOI18N

		jButton2.setAction(actionMap.get("up")); // NOI18N
		jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
		jButton2.setName("jButton2"); // NOI18N

		jButton3.setAction(actionMap.get("left")); // NOI18N
		jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
		jButton3.setName("jButton3"); // NOI18N

		jButton4.setAction(actionMap.get("right")); // NOI18N
		jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
		jButton4.setName("jButton4"); // NOI18N

		jButton5.setAction(actionMap.get("down")); // NOI18N
		jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
		jButton5.setName("jButton5"); // NOI18N

		jButton6.setAction(actionMap.get("zoom")); // NOI18N
		jButton6.setText(resourceMap.getString("jButton6.text")); // NOI18N
		jButton6.setName("jButton6"); // NOI18N

		jButton7.setAction(actionMap.get("dezoom")); // NOI18N
		jButton7.setText(resourceMap.getString("jButton7.text")); // NOI18N
		jButton7.setName("jButton7"); // NOI18N

		jButton8.setAction(actionMap.get("r")); // NOI18N
		jButton8.setText(resourceMap.getString("jButton8.text")); // NOI18N
		jButton8.setName("jButton8"); // NOI18N

		jButton9.setAction(actionMap.get("treeParse")); // NOI18N
		jButton9.setText(resourceMap.getString("jButton9.text")); // NOI18N
		jButton9.setName("jButton9"); // NOI18N

		final javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
		mainPanel.setLayout(mainPanelLayout);
		final ParallelGroup piece1 = mainPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
		final SequentialGroup piece3 = mainPanelLayout.createSequentialGroup();
		final SequentialGroup piece2 = piece3.addContainerGap();
		final ParallelGroup piece4 = piece1.addComponent(jLabel1);
		final ParallelGroup piece5 = piece4.addComponent(jLabel2).addComponent(jLabel3);
		final SequentialGroup piece6 = piece3
				.addComponent(jButton1)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addComponent(jCheckBox1);
		final SequentialGroup piece7 = piece3
				.addGroup(piece5)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(
						piece1.addComponent(ddBox)
								.addComponent(dBox)
								.addComponent(expressionBox,
										javax.swing.GroupLayout.DEFAULT_SIZE, 582,
										Short.MAX_VALUE));
		final SequentialGroup piece8 = piece3.addComponent(jPanel1,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);
		final ParallelGroup piece9 = mainPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
				.addComponent(jButton2).addComponent(jButton6)
				.addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING);
		final SequentialGroup piece23 = piece3.addComponent(jButton3)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(piece9);
		final SequentialGroup piece24 = piece3.addComponent(jButton8)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(jButton7);
		final ParallelGroup piece10 = mainPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
				.addGroup(piece23)
				.addGroup(javax.swing.GroupLayout.Alignment.LEADING, piece24);
		final SequentialGroup piece11 = piece3.addGroup(piece10);
		final SequentialGroup piece12 = piece11.addPreferredGap(
				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(jButton4);
		final ParallelGroup piece13 = mainPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
				.addGroup(piece12).addComponent(jButton9);
		final SequentialGroup piece14 = piece8.addPreferredGap(
				javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(piece13);
		final ParallelGroup piece15 = piece1.addGroup(piece7).addGroup(piece6)
				.addGroup(piece14);
		mainPanelLayout.setHorizontalGroup(piece1.addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING, piece2.addGroup(piece15)
						.addContainerGap()));
		final ParallelGroup piece16 = mainPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
				.addComponent(expressionBox, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel1);
		final ParallelGroup piece17 = mainPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
				.addComponent(jLabel3).addComponent(ddBox);
		final ParallelGroup piece18 = mainPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
				.addComponent(jLabel2).addComponent(dBox);
		final ParallelGroup piece19 = mainPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
				.addComponent(jButton1)
				.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jCheckBox1);
		final ParallelGroup piece20 = mainPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
				.addComponent(jButton4).addComponent(jButton6).addComponent(jButton3);
		final SequentialGroup piece21 = piece2.addGroup(piece16)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(piece18)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(piece17)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(piece19)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
		final ParallelGroup piece25 = mainPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
				.addComponent(jButton8).addComponent(jButton7);
		final SequentialGroup piece22 = piece3
				.addComponent(jButton2)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(piece20)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(jButton5)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(piece25)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190,
						Short.MAX_VALUE).addComponent(jButton9);
		mainPanelLayout.setVerticalGroup(piece1.addGroup(piece21.addGroup(
				piece1.addGroup(piece22).addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addContainerGap()));

		menuBar.setName("menuBar"); // NOI18N

		fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
		fileMenu.setName("fileMenu"); // NOI18N

		exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
		exitMenuItem.setName("exitMenuItem"); // NOI18N
		fileMenu.add(exitMenuItem);

		menuBar.add(fileMenu);

		setComponent(mainPanel);
		setMenuBar(menuBar);
	}// </editor-fold>//GEN-END:initComponents

	// ESCA-JAVA0173:
	private void expressionBoxFocusLost(final java.awt.event.FocusEvent evt){// GEN-FIRST:event_expressionBoxFocusLost
		try{
			final Expression expr = Parser.parse(expressionBox.getText());
			final Expression d = SimplificationHelper.simplify(DerivativeHelper.derivative(expr, 'x'));
			dBox.setText(Cleaner.clean(d.toString()));
			final Expression dd = SimplificationHelper.simplify(DerivativeHelper.derivative(d, 'x'));
			ddBox.setText(Cleaner.clean(dd.toString()));
		}
		catch(final ParserException ex){
			Log.log(LogLevel.ERROR, "Parser exception:", ex.getMessage());
		}
		catch(final DerivationException dex){
			Log.log(LogLevel.ERROR, "Derivation exception:", dex.getMessage());
		}
	}// GEN-LAST:event_expressionBoxFocusLost

	private void jPanel1KeyPressed(final java.awt.event.KeyEvent evt){// GEN-FIRST:event_jPanel1KeyPressed
		switch(evt.getKeyCode()){
			case KeyEvent.VK_NUMPAD5:
				zoom();
				break;
			case KeyEvent.VK_NUMPAD0:
				dezoom();
				break;

			case KeyEvent.VK_NUMPAD2:
			case KeyEvent.VK_UP:
				up();
				break;
			case KeyEvent.VK_NUMPAD4:
			case KeyEvent.VK_LEFT:
				left();
				break;
			case KeyEvent.VK_NUMPAD6:
			case KeyEvent.VK_RIGHT:
				right();
				break;
			case KeyEvent.VK_NUMPAD8:
			case KeyEvent.VK_DOWN:
				down();
				break;

			case KeyEvent.VK_R:
				r();
				break;

			default:
				break;
		}
	}// GEN-LAST:event_jPanel1KeyPressed

	@Action
	public void r(){
		dc.resetPosition();
		plot();
	}

	@Action
	public void down(){
		dc.goDown();
		plot();
	}

	@Action
	public void right(){
		dc.goRight();
		plot();
	}

	@Action
	public void left(){
		dc.goLeft();
		plot();
	}

	@Action
	public void up(){
		dc.goUp();
		plot();
	}

	@Action
	public void dezoom(){
		dc.zoomOut();
		plot();
	}

	@Action
	public void zoom(){
		dc.zoomIn();
		plot();
	}

	@Action
	public void treeParse(){
	}

	private void mainPanelKeyReleased(final java.awt.event.KeyEvent evt){// GEN-FIRST:event_mainPanelKeyReleased
		jPanel1KeyPressed(evt);
	}// GEN-LAST:event_mainPanelKeyReleased

	private void jButton1KeyPressed(final java.awt.event.KeyEvent evt){// GEN-FIRST:event_jButton1KeyPressed
		jPanel1KeyPressed(evt);
	}// GEN-LAST:event_jButton1KeyPressed

	private void expressionBoxKeyPressed(final java.awt.event.KeyEvent evt){// GEN-FIRST:event_expressionBoxKeyPressed
		if(evt.getKeyCode() == KeyEvent.VK_ENTER){
			plot();
			jButton1.requestFocus();
		}
	}// GEN-LAST:event_expressionBoxKeyPressed
		// Variables declaration - do not modify//GEN-BEGIN:variables

	private javax.swing.JLabel dBox;
	private javax.swing.JLabel ddBox;
	private javax.swing.JTextField expressionBox;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel mainPanel;
	private javax.swing.JMenuBar menuBar;
	// End of variables declaration//GEN-END:variables
	private JDialog aboutBox;
}
